name: Generate radar chart

on:
  schedule:
    - cron: "0 0 * * *"   # runs once per day
  workflow_dispatch:       # lets you trigger it manually

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_radar: yes
          plugin_radar_sections: repositories, commits, issues, pull_requests, reviews
