name: Generate radar chart
on:
  # update once a day
  schedule: [{cron: "0 0 * * *"}]
  # allow manual trigger
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_radar: yes
          plugin_radar_sections: repositories, commits, issues, pull_requests, reviews
